import pandas as pd
import joblib
import os
import uuid
from backend.ml.feature_engineering import engineer_features

class Predictor:
    def __init__(self, models_dir: str = "backend/ml/models_storage"):
        self.models_dir = models_dir
        self.active_models = {} # Cache loaded models

    def load_model(self, file_path: str):
        full_path = os.path.join(self.models_dir, os.path.basename(file_path))
        if not os.path.exists(full_path):
            raise FileNotFoundError(f"Model file not found: {full_path}")

        data = joblib.load(full_path)
        return data['preprocessor'], data['model']

    def predict_sla_breach(self, file_path: str, input_data: dict):
        # 1. Convert input dict to DataFrame
        df = pd.DataFrame([input_data])

        # 2. Load model & preprocessor
        if file_path not in self.active_models:
            self.active_models[file_path] = self.load_model(file_path)

        preprocessor, model = self.active_models[file_path]

        # 3. Engineer Features
        df_engineered = engineer_features(df)

        # Determine expected feature columns from the preprocessor's knowledge if needed,
        # but the safest way is to just pass it through the preprocessor

        # The preprocessor expects the base features that were originally passed.
        # Drop target columns generated by engineer_features if they exist
        drop_cols = ['sla_breach', 'transit_days']
        df_to_transform = df_engineered.drop(columns=[c for c in drop_cols if c in df_engineered.columns])

        df_processed = preprocessor.transform(df_to_transform)

        # The model needs the columns in the exact order it was trained on.
        # If we saved the training feature names, we should reorder.
        # For simplicity, assuming df_processed has the exact same layout.
        # In a strict production system, model_training would save feature_names
        # and we would do: df_processed = df_processed[feature_names]

        prediction = model.predict(df_processed)[0]

        probability = 0.0
        if hasattr(model, 'predict_proba'):
            # probability of the positive class (breach)
            prob_arr = model.predict_proba(df_processed)
            if prob_arr.shape[1] > 1:
                probability = float(prob_arr[0][1])
            else:
                probability = float(prob_arr[0][0])

        # Risk level logic
        if probability < 0.2:
            risk_level = "Very Low"
        elif probability < 0.4:
            risk_level = "Low"
        elif probability < 0.6:
            risk_level = "Medium"
        elif probability < 0.8:
            risk_level = "High"
        else:
            risk_level = "Critical"

        return {
            "prediction_id": str(uuid.uuid4()),
            "predicted_sla_breach": bool(prediction),
            "delay_probability": probability,
            "risk_level": risk_level,
            "confidence_score": max(probability, 1 - probability),
            "expected_transit_days": float(input_data.get("transit_days_expected", input_data.get("expected_transit_days", 0.0)))
        }
